name: Collect ActBlue ticker value

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes

jobs:
  scrape:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.auto-commit-action.outputs.commit_hash }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run scraper
        id: scraper
        run: ./scrape.sh

      - name: Commit sitewide_raised_amount.txt to GitHub
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Changed by ${{ env.difference }}
          file_pattern: sitewide_raised_amount.txt

  insert:
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.scrape.outputs.commit_hash }}

      - name: Run inserter
        id: inserter
        run: ./insert.sh

      - name: Commit amounts.csv to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: amounts.csv updated
          file_pattern: amounts.csv
